"""Add bill and debt fields to mocked user

Revision ID: 93fd2ca5ad3c
Revises: 607a80ce2682
Create Date: 2025-07-11 23:41:50.979129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fd2ca5ad3c'
down_revision: Union[str, Sequence[str], None] = '607a80ce2682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('light_bill', sa.Integer(), nullable=True))
    op.add_column('user_data', sa.Column('heat_bill', sa.Integer(), nullable=True))
    op.add_column('user_data', sa.Column('electricity_bill', sa.Integer(), nullable=True))
    op.add_column('user_data', sa.Column('debt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'debt')
    op.drop_column('user_data', 'electricity_bill')
    op.drop_column('user_data', 'heat_bill')
    op.drop_column('user_data', 'light_bill')
    # ### end Alembic commands ###
