"""add question_label_column

Revision ID: 5613bb87b082
Revises: b496d67581e4
Create Date: 2025-07-10 15:53:36.133675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5613bb87b082'
down_revision: Union[str, Sequence[str], None] = 'b496d67581e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('question_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'question_label')
    # ### end Alembic commands ###
